### ISSUE TITLE
Chỉnh sửa viền một số chỗ không phù hợp

### ISSUE THREAD

**Issue by Flushz** [MinhCao031/Web3306_22#119]
Bỏ viền hoặc chuyển viền sang vuông góc chứ không để bo ở các cột Lớp và Chức vụ trong ảnh
![image](https://user-images.githubusercontent.com/54463108/143896778-b80ac87a-37e8-4712-9a18-bcff8c509db5.png)

![image](https://user-images.githubusercontent.com/54463108/143897007-737f5222-1171-4d74-b9bf-ff9b1b1857ff.png)

**Comment by mnquang02122001** [comment]
done
