### ISSUE TITLE
Căn chỉnh các nút 

### ISSUE THREAD

**Issue by Flushz** [MinhCao031/Web3306_22#122]
Chỉnh lại vị trí các nút:
- Upload/Download file thẳng hàng với các nút chọn trang
- Lưu/Hủy thẳng cột với nút chọn trang
![image](https://user-images.githubusercontent.com/54463108/143903827-770b46fb-5087-4784-9b8e-90df56477dba.png)

**Comment by Flushz** [comment]
@mnquang02122001 Ừ nma hai nút Upload/Download có đẩy lên ngang hàng với mấy nút bị cố định được không ông?

**Comment by mnquang02122001** [comment]
Có vẻ không ông ạ, tại 2 nút chọn trang với số trang t dùng lib nên cả cái hàng chứa 2 nút đấy là 1 thẻ div rồi

**Comment by mnquang02122001** [comment]
Được nhé
