### ISSUE TITLE
Lỗi tại phần hiển thị danh sách sinh viên trong lớp

### ISSUE THREAD

**Issue by thanhtvt** [MinhCao031/Web3306_22#55]
Khi tương tác với một số thành phần trong trang thì các thành phần khác cứ lắc lư quanh vị trí ban đầu (có vẻ giống mở rộng width của trang hơn
Demo (anh em bỏ qua cái hình bên cạnh nhé, nó record cả 2 màn hình mà t ko biết =))) )
https://user-images.githubusercontent.com/62584583/141971965-31a11885-5b70-4174-9a8d-e0b2ac1a1c0d.mp4

)

**Comment by mnquang02122001** [comment]
Đã fix
