### ISSUE TITLE
Điều kiện chỉnh sửa chức vụ

### ISSUE THREAD

**Issue by thanhtvt** [MinhCao031/Web3306_22#64]
Trong cùng một lớp chỉ có 1 lớp trưởng + 1 bí thư. Hiện tại hệ thống chưa xử lý cái này
![image](https://user-images.githubusercontent.com/62584583/142098620-6baa84c0-fe6a-4387-abb4-904415846b2e.png)

**Comment by mnquang02122001** [comment]
Đã fix
