### ISSUE TITLE
Tìm kiếm ngày tháng chưa hoàn thiện

### ISSUE THREAD

**Issue by thanhtvt** [MinhCao031/Web3306_22#65]
Như demo ảnh bên dưới, có 2 record có ngày sinh là 28/02/2001 nhưng khi gõ 28/ là không tìm được ai nữa
![image](https://user-images.githubusercontent.com/62584583/142100589-7ae91d5c-0df7-453d-86c8-cb6c10efaea9.png)
![image](https://user-images.githubusercontent.com/62584583/142100744-271c3807-9ab4-4b80-9da4-09d715a57447.png)

**Comment by mnquang02122001** [comment]
Đã fix
